### ISSUE TITLE
jwt.decode(None) causeAttributeError: 'NoneType' object has no attribute 'rsplit'

### ISSUE THREAD

**Issue by guyskk** [jpadilla/pyjwt#183]
```python
>>> import jwt
>>> jwt.decode(None)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Python27\lib\site-packages\jwt\api_jwt.py", line 61, in decode
    payload, signing_input, header, signature = self._load(jwt)
  File "C:\Python27\lib\site-packages\jwt\api_jws.py", line 135, in _load
    signing_input, crypto_segment = jwt.rsplit(b'.', 1)
AttributeError: 'NoneType' object has no attribute 'rsplit'
>>> 
```

It should raise jwt.InvalidTokenError.

**Comment by maoaiz** [comment]
I have the same issue.

I think the solution is here: https://github.com/jpadilla/pyjwt/blob/master/jwt/api_jws.py#L135

Change the lines 135 and 136 to:

    if not isinstance(jwt, text_type):
        raise DecodeError('Invalid token')

    jwt = jwt.encode('utf-8')
