### ISSUE TITLE
Failure at decoding: TypeError: ord() expected string of length 1, but int found

### ISSUE THREAD

**Issue by CasperCLD** [jpadilla/pyjwt#185]
I've installed: python3-dev, libffi-dev, PyJWT and cryptography. I'm using a virtual environment.
See stack trace: 

```
>>> import jwt
>>> encoded = jwt.encode({'some': 'payload'}, 'secret', algorithm='HS256')
>>> jwt.encode({'some': 'payload'}, 'secret', algorithm='HS256', headers={'kid': '230498151c214b788dd97f22b85410a5'})
KeyboardInterrupt
>>> jwt.decode(encoded, 'secret', algorithms=['HS256'])
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/casper/env/PyJWT-playground/lib/python3.2/site-packages/jwt/api_jwt.py", line 64, in decode
    options, **kwargs)
  File "/home/casper/env/PyJWT-playground/lib/python3.2/site-packages/jwt/api_jws.py", line 115, in decode
    key, algorithms)
  File "/home/casper/env/PyJWT-playground/lib/python3.2/site-packages/jwt/api_jws.py", line 177, in _verify_signature
    if not alg_obj.verify(signing_input, key, signature):
  File "/home/casper/env/PyJWT-playground/lib/python3.2/site-packages/jwt/algorithms.py", line 138, in verify
    return constant_time_compare(sig, self.sign(msg, key))
  File "/home/casper/env/PyJWT-playground/lib/python3.2/site-packages/jwt/compat.py", line 50, in constant_time_compare
    result |= ord(x) ^ ord(y)
TypeError: ord() expected string of length 1, but int found
```

Am I doing something wrong?
OS: Rasbian (latest 2015-09-24)

**Comment by mark-adams** [comment]
This is happening because PyJWT is not supported on Python 3.2. That version of Python has some weird quirks and since `cryptography` doesn't support it either, we decided to stop supporting it beginning with 1.3.0.

I'd recommend that you upgrade to Python 3.3 or later.

**Comment by CasperCLD** [comment]
Ah all right, thanks.
