### ISSUE TITLE
False positive decode

### ISSUE THREAD

**Issue by jomag** [jpadilla/pyjwt#223]
Hi

I have this problem where a test every now and then get a false positive decode of a JWT token. In the test I take a valid token and replace the last character with 'x' (making sure that the last character was not already 'x').

Here's an example where two different data sets are successfully decoded:

```
Python 3.4.2 (default, Oct  8 2014, 10:45:20) 
[GCC 4.9.1] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import jwt
>>> jwt.decode('eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJzdmVuc3NvbiIsImlhdCI6MTQ3NjE5NjE5MX0.enG1NgSOpr2bsDaa7JzpBT1kFaP5AOvqigv8Y56w8Qw', 'VerySecretSecret')
{'iat': 1476196191, 'sub': 'svensson'}
>>> jwt.decode('eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJzdmVuc3NvbiIsImlhdCI6MTQ3NjE5NjE5MX0.enG1NgSOpr2bsDaa7JzpBT1kFaP5AOvqigv8Y56w8Qx', 'VerySecretSecret')                                                                                                                      
{'iat': 1476196191, 'sub': 'svensson'}
>>> jwt.decode('eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJzdmVuc3NvbiIsImlhdCI6MTQ3NjE5NjE5MX0.enG1NgSOpr2bsDaa7JzpBT1kFaP5AOvqigv8Y56w8Qy', 'VerySecretSecret')
{'iat': 1476196191, 'sub': 'svensson'}
>>> jwt.decode('eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJzdmVuc3NvbiIsImlhdCI6MTQ3NjE5NjE5MX0.enG1NgSOpr2bsDaa7JzpBT1kFaP5AOvqigv8Y56w8Qz', 'VerySecretSecret')
{'iat': 1476196191, 'sub': 'svensson'}
>>> jwt.decode('eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJzdmVuc3NvbiIsImlhdCI6MTQ3NjE5NjE5MX0.enG1NgSOpr2bsDaa7JzpBT1kFaP5AOvqigv8Y56w8Qv', 'VerySecretSecret')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/jonatan/src/myeden.se/.env/lib/python3.4/site-packages/jwt/api_jwt.py", line 64, in decode
    options, **kwargs)
  File "/home/jonatan/src/myeden.se/.env/lib/python3.4/site-packages/jwt/api_jws.py", line 116, in decode
    key, algorithms)
  File "/home/jonatan/src/myeden.se/.env/lib/python3.4/site-packages/jwt/api_jws.py", line 186, in _verify_signature
    raise DecodeError('Signature verification failed')
jwt.exceptions.DecodeError: Signature verification failed
>
```

In this example the correct token is the first one, which ends with 'w'.

Is this expected behavior?

**Comment by jomag** [comment]
I've tested with the tools at http://jwt.io as well with same result, so this is most likely not a problem.
