### ISSUE TITLE
InvalidAlgorithmError with 1.5.1 release

### ISSUE THREAD

**Issue by Prince-Leto** [jpadilla/pyjwt#278]
When updating PyJWT from 1.5.0 to 1.5.1, my Django project does not work anymore.
Using django-rest-framework, and django-rest-framework-jwt.

```
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/rest_framework_jwt/authentication.py", line 33, in authenticate
    payload = jwt_decode_handler(jwt_value)
  File "/usr/local/lib/python3.6/site-packages/rest_framework_jwt/utils.py", line 113, in jwt_decode_handler
    algorithms=[api_settings.JWT_ALGORITHM]
  File "/usr/local/lib/python3.6/site-packages/jwt/api_jwt.py", line 77, in decode
    **kwargs)
  File "/usr/local/lib/python3.6/site-packages/jwt/api_jws.py", line 135, in decode
    key, algorithms)
  File "/usr/local/lib/python3.6/site-packages/jwt/api_jws.py", line 199, in _verify_signature
    raise InvalidAlgorithmError('The specified alg value is not allowed')
jwt.exceptions.InvalidAlgorithmError: The specified alg value is not allowed
```

The code responsible of this issue:  
```python
def _verify_signature(self, payload, signing_input, header, signature,
                          key='', algorithms=None):
        alg = header.get('alg')
        if algorithms is not None and alg not in algorithms:
            raise InvalidAlgorithmError('The specified alg value is not allowed') ...
        try:
            alg_obj = self._algorithms[alg]
            key = alg_obj.prepare_key(key)
            if not alg_obj.verify(signing_input, key, signature):
```

And local vars are:
alg: `'HS256'`
algorithms: `{'verify_exp': True, 'verify_signature': True}`
header: `{'alg': 'HS256', 'typ': 'JWT'}`

**Comment by jpadilla** [comment]
Released [v1.5.2](https://github.com/jpadilla/pyjwt/releases/tag/1.5.2) to fix this
