### ISSUE TITLE
ValueError: Could not deserialize key data.

### ISSUE THREAD

**Issue by sushovan23** [jpadilla/pyjwt#328]
Here is my code:

```
    keyfile = open ("pubkey.pem", 'r')
    keystring = keyfile.read()

    print keystring
    decoded = jwt.decode(encoded, keystring, algorithms='RS256')
```
pubkey.pem is RSA key starting with:
```
-----BEGIN CERTIFICATE-----
cert values
-----END CERTIFICATE-----
```
stacktrace:

```
Traceback (most recent call last):
  File "oauth_test.py", line 47, in <module>
    main()
  File "oauth_test.py", line 44, in main
    decoded = jwt.decode(encoded, keystring, algorithms='RS256')
  File "/usr/lib/python2.7/site-packages/jwt/api_jwt.py", line 78, in decode
    jwt, key=key, algorithms=algorithms, options=options, **kwargs
  File "/usr/lib/python2.7/site-packages/jwt/api_jws.py", line 140, in decode
    key, algorithms)
  File "/usr/lib/python2.7/site-packages/jwt/api_jws.py", line 204, in _verify_signature
    key = alg_obj.prepare_key(key)
  File "/usr/lib/python2.7/site-packages/jwt/algorithms.py", line 207, in prepare_key
    key = load_pem_public_key(key, backend=default_backend())
  File "/usr/lib64/python2.7/site-packages/cryptography/hazmat/primitives/serialization.py", line 24, in load_pem_public_key
    return backend.load_pem_public_key(data)
  File "/usr/lib64/python2.7/site-packages/cryptography/hazmat/backends/openssl/backend.py", line 1041, in load_pem_public_key
    self._handle_key_loading_error()
  File "/usr/lib64/python2.7/site-packages/cryptography/hazmat/backends/openssl/backend.py", line 1292, in _handle_key_loading_error
    raise ValueError("Could not deserialize key data.")
```
Please let me know where I may be going wrong.

**Comment by sushovan23** [comment]
Issue was with using cert instead of pubkey. I had to convert the cert to pubkey plaintext and then read it. It working

**Comment by Allan-Nava** [comment]
@sushovan23  how do you solve the problem?

**Comment by sushovan23** [comment]
I have to convert the cert file - 

openssl x509 -in certificate.cer -pubkey -noout > publickey.txt

**Comment by Allan-Nava** [comment]
@sushovan23 I used the keycloak to get the jwt but I want to implement with django restframework-jwt and keycloak. Is possible?
