### ISSUE TITLE
Encoding JWS with a dictionary payload

### ISSUE THREAD

**Issue by trevh3** [jpadilla/pyjwt#385]
## Summary
Are dictionaries supported when encoding a JWS? The comments seem to support this use case, but the error message I receive indicates that only bytes-like variables are supported.

## Reproduction Steps

```python
from jwt.api_jws import PyJWS
  
jws = PyJWS()
payload = {'hello':'world'}
secret = 'mysecret'

jws.encode(payload, secret, algorithm='ES256')
```

Response: 
```
Traceback (most recent call last):
  File "test.py", line 7, in <module>
    jws.encode(payload, secret, algorithm='ES256')
  File "/Users/thutton/miniconda3/lib/python3.7/site-packages/jwt/api_jws.py", line 108, in encode
    segments.append(base64url_encode(payload))
  File "/Users/thutton/miniconda3/lib/python3.7/site-packages/jwt/utils.py", line 46, in base64url_encode
    return base64.urlsafe_b64encode(input).replace(b'=', b'')
  File "/Users/thutton/miniconda3/lib/python3.7/base64.py", line 118, in urlsafe_b64encode
    return b64encode(s).translate(_urlsafe_encode_translation)
  File "/Users/thutton/miniconda3/lib/python3.7/base64.py", line 58, in b64encode
    encoded = binascii.b2a_base64(s, newline=False)
TypeError: a bytes-like object is required, not 'dict'
```

## System Information

    $ python -m jwt.help

```
{
  "cryptography": {
    "version": "2.3.1"
  },
  "implementation": {
    "name": "CPython",
    "version": "3.7.0"
  },
  "platform": {
    "release": "18.2.0",
    "system": "Darwin"
  },
  "pyjwt": {
    "version": "1.6.4"
  }
}
```

This command is only available on PyJWT v1.6.3 and greater. Otherwise,
please provide some basic information about your system.

**Comment by vimalloc** [comment]
Instead try:

```python
import jwt

payload = {'hello':'world'}
secret = 'mysecret'

# If you want to use ES256 you will need to generate public/private keypair. 
jwt.encode(payload, secret, algorithm='HS256')
```

**Comment by trevh3** [comment]
That works well. The comment just indicates that dictionaries are accepted.
