### ISSUE TITLE
Error decoding on command-line: Expected a string value

### ISSUE THREAD

**Issue by jaraco** [jpadilla/pyjwt#412]
Running a simple `decode` operation on the command line fails on Python 3:

```
$ pyjwt decode                                                                                                                                    
eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJ1c2VyX2lkIjoxMjM0NTYsIm5hbWUiOiJcImphcmFjbyBkZXZcIiIsImFkbWluIjp0cnVlfQ.sx1EqsdNkZ2IAkDGmqs6PCjFPG0XNvtAYvlMXmyIG4g
There was an unforseen error:  Expected a string value
usage: 
    Encodes or decodes JSON Web Tokens based on input.

...
```

**Comment by jaraco** [comment]
Aha. The issue is that either `--key` or `--no-verify` must be passed, but if it's not, it triggers the reported error. Allowing the traceback to propagate, it's more clear what's happening:

```
Traceback (most recent call last):
  File ".tox/python/bin/pyjwt", line 10, in <module>
    sys.exit(main())
  File "/Users/jaraco/code/public/pyjwt/.tox/python/lib/python3.7/site-packages/jwt/__main__.py", line 162, in main
    output = arguments.func(arguments)
  File "/Users/jaraco/code/public/pyjwt/.tox/python/lib/python3.7/site-packages/jwt/__main__.py", line 65, in decode_payload
    data = decode(token, key=args.key, verify=args.verify)
  File "/Users/jaraco/code/public/pyjwt/.tox/python/lib/python3.7/site-packages/jwt/api_jwt.py", line 93, in decode
    jwt, key=key, algorithms=algorithms, options=options, **kwargs
  File "/Users/jaraco/code/public/pyjwt/.tox/python/lib/python3.7/site-packages/jwt/api_jws.py", line 156, in decode
    key, algorithms)
  File "/Users/jaraco/code/public/pyjwt/.tox/python/lib/python3.7/site-packages/jwt/api_jws.py", line 220, in _verify_signature
    key = alg_obj.prepare_key(key)
  File "/Users/jaraco/code/public/pyjwt/.tox/python/lib/python3.7/site-packages/jwt/algorithms.py", line 140, in prepare_key
    key = force_bytes(key)
  File "/Users/jaraco/code/public/pyjwt/.tox/python/lib/python3.7/site-packages/jwt/utils.py", line 30, in force_bytes
    raise TypeError('Expected a string value')
TypeError: Expected a string value
```

**Comment by jaraco** [comment]
I suggest the command-line handler should probably emit a nicer message when `args.verify` but not `args.key`.

**Comment by jpadilla** [comment]
cli entrypoint has been removed
