### ISSUE TITLE
Getting exception NameError: global name 'decode_rfc6979_signature' is not defined

### ISSUE THREAD

**Issue by tayalakansh** [jpadilla/pyjwt#474]
Summary.
Getting exception on Ubuntu 14.04.5 LTS and PyJWT-1.7.1
## Expected Result

What you expected.

## Actual Result

Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 2311, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1834, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1737, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1832, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1818, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "./application.py", line 182, in push_ios_today_cases
    return push_today_cases()
  File "./ios.py", line 76, in push_today_cases
    'kid': 'LPSB786QW9'
  File "/usr/local/lib/python2.7/dist-packages/jwt/api_jwt.py", line 56, in encode
    json_payload, key, algorithm, headers, json_encoder
  File "/usr/local/lib/python2.7/dist-packages/jwt/api_jws.py", line 98, in encode
    signature = alg_obj.sign(signing_input, key)
  File "/usr/local/lib/python2.7/dist-packages/jwt/algorithms.py", line 239, in sign
    return der_to_raw_signature(der_sig, key.curve)
  File "/usr/local/lib/python2.7/dist-packages/jwt/utils.py", line 52, in der_to_raw_signature
    r, s = decode_rfc6979_signature(der_sig)
NameError: global name 'decode_rfc6979_signature' is not defined

## Reproduction Steps

```python
import jwt

```

## System Information

    $ python -m jwt.help

```
{
  "cryptography": {
    "version": "2.8"
  },
  "implementation": {
    "name": "CPython",
    "version": "2.7.6"
  },
  "platform": {
    "release": "3.13.0-105-generic",
    "system": "Linux"
  },
  "pyjwt": {
    "version": "1.7.1"
  }
}
```

This command is only available on PyJWT v1.6.3 and greater. Otherwise,
please provide some basic information about your system.

**Comment by tayalakansh** [comment]
Uninstalling and installing cryptography and pyjwt fixed the issue.
