### ISSUE TITLE
v2.0.0 decode() gets ValueError: Could not deserialize key data.

### ISSUE THREAD

**Issue by qrkourier** [jpadilla/pyjwt#588]
Summary.
After upgrading to v2.0.0 there is a reproducible problem with decoding a JWT.

## Expected Result

```python
python3 -c 'import os; import jwt; import json; claim = jwt.decode(os.environ["TOKEN"], verify=False); print(json.dumps(claim, indent=4))'
```

gets

```json
{
    "sub": "5becmdmunn8blbun48vsdrmjd",
    "token_use": "access",
    "scope": "https://gateway.production.netfoundry.io//ignore-scope",
    "auth_time": 1608778068,
    "iss": "https://cognito-idp.us-east-1.amazonaws.com/us-east-1_3uDA8bXTz",
    "exp": 1608781668,
    "iat": 1608778068,
    "version": 2,
    "jti": "6ec71023-2910-439f-9230-6360c9c45adf",
    "client_id": "5becmdqlni9blbun48vsdrmjd"
}
```

## Actual Result

After adding the now-mandatory "algorithms" parameter the decode() method gets ValueError

## Reproduction Steps

Assign an RS256 JWT to environment var TOKEN
```python
python3 -c 'import os; import jwt; jwt.decode(os.environ["TOKEN"], verify=False, algorithms=["RS256"])'
Traceback (most recent call last):
  File "/home/kbingham/.pyenv/versions/3.8.0/lib/python3.8/site-packages/jwt/algorithms.py", line 242, in prepare_key
    key = load_pem_private_key(key, password=None)
  File "/home/kbingham/.pyenv/versions/3.8.0/lib/python3.8/site-packages/cryptography/hazmat/primitives/serialization/base.py", line 18, in load_pem_private_key
    return backend.load_pem_private_key(data, password)
  File "/home/kbingham/.pyenv/versions/3.8.0/lib/python3.8/site-packages/cryptography/hazmat/backends/openssl/backend.py", line 1244, in load_pem_private_key
    return self._load_key(
  File "/home/kbingham/.pyenv/versions/3.8.0/lib/python3.8/site-packages/cryptography/hazmat/backends/openssl/backend.py", line 1475, in _load_key
    self._handle_key_loading_error()
  File "/home/kbingham/.pyenv/versions/3.8.0/lib/python3.8/site-packages/cryptography/hazmat/backends/openssl/backend.py", line 1517, in _handle_key_loading_error
    raise ValueError(
ValueError: Could not deserialize key data. The data may be in an incorrect format or it may be encrypted with an unsupported algorithm.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/home/kbingham/.pyenv/versions/3.8.0/lib/python3.8/site-packages/jwt/api_jwt.py", line 113, in decode
    decoded = self.decode_complete(jwt, key, algorithms, options, **kwargs)
  File "/home/kbingham/.pyenv/versions/3.8.0/lib/python3.8/site-packages/jwt/api_jwt.py", line 83, in decode_complete
    decoded = api_jws.decode_complete(
  File "/home/kbingham/.pyenv/versions/3.8.0/lib/python3.8/site-packages/jwt/api_jws.py", line 149, in decode_complete
    self._verify_signature(signing_input, header, signature, key, algorithms)
  File "/home/kbingham/.pyenv/versions/3.8.0/lib/python3.8/site-packages/jwt/api_jws.py", line 233, in _verify_signature
    key = alg_obj.prepare_key(key)
  File "/home/kbingham/.pyenv/versions/3.8.0/lib/python3.8/site-packages/jwt/algorithms.py", line 244, in prepare_key
    key = load_pem_public_key(key)
  File "/home/kbingham/.pyenv/versions/3.8.0/lib/python3.8/site-packages/cryptography/hazmat/primitives/serialization/base.py", line 23, in load_pem_public_key
    return backend.load_pem_public_key(data)
  File "/home/kbingham/.pyenv/versions/3.8.0/lib/python3.8/site-packages/cryptography/hazmat/backends/openssl/backend.py", line 1274, in load_pem_public_key
    self._handle_key_loading_error()
  File "/home/kbingham/.pyenv/versions/3.8.0/lib/python3.8/site-packages/cryptography/hazmat/backends/openssl/backend.py", line 1517, in _handle_key_loading_error
    raise ValueError(
ValueError: Could not deserialize key data. The data may be in an incorrect format or it may be encrypted with an unsupported algorithm.
```

## System Information

    $ python -m jwt.help

```json
{
  "cryptography": {
    "version": "3.3.1"
  },
  "implementation": {
    "name": "CPython",
    "version": "3.8.0"
  },
  "platform": {
    "release": "5.8.0-7630-generic",
    "system": "Linux"
  },
  "pyjwt": {
    "version": "2.0.0"
  }
}
```

**Comment by qrkourier** [comment]
When I paste the same JWT in jwt.io I get header

```json
{
  "kid": "Ae4DkySQaQf4bpCsGwS8/BXpv2IeVAJZJUHTtuKIlBU=",
  "alg": "RS256"
}
```

**Comment by qrkourier** [comment]
Here's [an example JWT](https://jwt.io/#debugger-io?token=eyJraWQiOiI1SWE4TTZmeTBnUUpCQzIwV3BNVGlVMjRZV3BYU2FRMW12V3ZXQXRLbm9FPSIsImFsZyI6IlJTMjU2In0.eyJzdWIiOiIzY291OHZmdnJ0MW02cHQxN2FpMGdwZ3JpcSIsInRva2VuX3VzZSI6ImFjY2VzcyIsInNjb3BlIjoiaHR0cHM6XC9cL2dhdGV3YXkuc2FuZGJveC5uZXRmb3VuZHJ5LmlvXC9cL2lnbm9yZS1zY29wZSIsImF1dGhfdGltZSI6MTYwODc4MDI2NSwiaXNzIjoiaHR0cHM6XC9cL2NvZ25pdG8taWRwLnVzLWVhc3QtMS5hbWF6b25hd3MuY29tXC91cy1lYXN0LTFfYWVJZWZnMXJtIiwiZXhwIjoxNjA4NzgzODY1LCJpYXQiOjE2MDg3ODAyNjUsInZlcnNpb24iOjIsImp0aSI6IjBkYTc5ZGUxLTUyODEtNGUzOS1iZGEwLTU2YTBmNmNlNmEyZCIsImNsaWVudF9pZCI6IjNjb3U4dmZ2cnQxbTZwdDE3YWkwZ3BncmlxIn0.knoClda2sKgxxa3McTR_cRVa36SrtmjU3LBbj6EOka0XXF490x2ADmJnWVbtXEUOzwVw3gOdOMegYFmavv5OjnKBUwdaVpRwibrJcUAjTZBq9U37kx4SsawAOuiEfN0nLskeYPNMYN18Q8MdoIxQ4LNzwH7vkMCiH2cucilGeGTCQxiMVH13QHFIX78qtD8Cm7V-SVufnJvIl8g4umwyqE1tm9qkFFa5RCLhgZ64O1XfQj1ooDwsTziUMN052VjbNQTW_jMT0XDHBrHKe5b9TPbYX04YXD45y1vRC19m5wGjVsCn0q7Co4zWShUCrVcoLYzOkhVpxp05zmPOQlrbjg&publicKey=-----BEGIN%20PUBLIC%20KEY-----%0AMIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAmj9C3lKLe%2Fr40jDNKOr3%0AYQKClMYouxLlK6nx35n4s8XAv0C8p%2FRhxjdEfnBYGW6S2AeqFprDRg5hM8WWTPxW%0AxqdDv7XhoMI2ykxrg%2FfQ9EH%2Fhl8OJkJhjVZ8ke2rPDqJOBvAmHqTO8%2B0toqPFPS2%0AOoA1DpQ9ZtqWg67elSbeUQIKcxl2oB%2FQUB97vqjKj8XdRWX4xz%2FGiARNwjIkIOkU%0AJYsVeYh1xUJYdaIv3%2FMdJwlKNkJOJbclBAv9ZxWzSGENBkBv2yJJVr8enjsa6e8k%0AYAgHqNFpC4gmhgnv80p2%2BH%2FYAVJ%2BKNsvZxe%2F9pwPwvBLBY2qDde%2BGin%2BWrffr%2B7R%0AMQIDAQAB%0A-----END%20PUBLIC%20KEY-----%0A) that triggers this error.

**Comment by jpadilla** [comment]
```
TOKEN="eyJraWQiOiI1SWE4TTZmeTBnUUpCQzIwV3BNVGlVMjRZV3BYU2FRMW12V3ZXQXRLbm9FPSIsImFsZyI6IlJTMjU2In0.eyJzdWIiOiIzY291OHZmdnJ0MW02cHQxN2FpMGdwZ3JpcSIsInRva2VuX3VzZSI6ImFjY2VzcyIsInNjb3BlIjoiaHR0cHM6XC9cL2dhdGV3YXkuc2FuZGJveC5uZXRmb3VuZHJ5LmlvXC9cL2lnbm9yZS1zY29wZSIsImF1dGhfdGltZSI6MTYwODc4MDI2NSwiaXNzIjoiaHR0cHM6XC9cL2NvZ25pdG8taWRwLnVzLWVhc3QtMS5hbWF6b25hd3MuY29tXC91cy1lYXN0LTFfYWVJZWZnMXJtIiwiZXhwIjoxNjA4NzgzODY1LCJpYXQiOjE2MDg3ODAyNjUsInZlcnNpb24iOjIsImp0aSI6IjBkYTc5ZGUxLTUyODEtNGUzOS1iZGEwLTU2YTBmNmNlNmEyZCIsImNsaWVudF9pZCI6IjNjb3U4dmZ2cnQxbTZwdDE3YWkwZ3BncmlxIn0.knoClda2sKgxxa3McTR_cRVa36SrtmjU3LBbj6EOka0XXF490x2ADmJnWVbtXEUOzwVw3gOdOMegYFmavv5OjnKBUwdaVpRwibrJcUAjTZBq9U37kx4SsawAOuiEfN0nLskeYPNMYN18Q8MdoIxQ4LNzwH7vkMCiH2cucilGeGTCQxiMVH13QHFIX78qtD8Cm7V-SVufnJvIl8g4umwyqE1tm9qkFFa5RCLhgZ64O1XfQj1ooDwsTziUMN052VjbNQTW_jMT0XDHBrHKe5b9TPbYX04YXD45y1vRC19m5wGjVsCn0q7Co4zWShUCrVcoLYzOkhVpxp05zmPOQlrbjg" python3 -c 'import os; import jwt; import json; claim = jwt.decode(os.environ["TOKEN"], algorithms=["RS256"], options={"verify_signature": False}); print(json.dumps(claim, indent=4))'
```

[The verify param is not supported anymore](https://github.com/jpadilla/pyjwt/blob/master/CHANGELOG.md#dropped-deprecated-verify-param-in-jwtdecode)

**Comment by mcepl** [comment]
The links is https://github.com/jpadilla/pyjwt/blob/master/CHANGELOG.rst#dropped-deprecated-verify-param-in-jwtdecode now.
