### ISSUE TITLE
Seeing issues in decode

### ISSUE THREAD

**Issue by sarangdharmapurikar1** [jpadilla/pyjwt#619]
With the latest version I see these errors. What can I do to fix these? I just want to decode the token without verifying.

>>> **jwt.decode(encoded_jwt, verify=False, algorithms=['RS256'])**
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python3.9/site-packages/jwt/api_jwt.py", line 113, in decode
    decoded = self.decode_complete(jwt, key, algorithms, options, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/jwt/api_jwt.py", line 88, in decode_complete
    **kwargs,
  File "/usr/local/lib/python3.9/site-packages/jwt/api_jws.py", line 149, in decode_complete
    self._verify_signature(signing_input, header, signature, key, algorithms)
  File "/usr/local/lib/python3.9/site-packages/jwt/api_jws.py", line 233, in _verify_signature
    key = alg_obj.prepare_key(key)
  File "/usr/local/lib/python3.9/site-packages/jwt/algorithms.py", line 250, in prepare_key
    key = load_pem_private_key(key, password=None)
  File "/usr/local/lib/python3.8/site-packages/cryptography/hazmat/primitives/serialization/base.py", line 17, in load_pem_private_key
    backend = _get_backend(backend)
  File "/usr/local/lib/python3.8/site-packages/cryptography/hazmat/backends/__init__.py", line 24, in _get_backend
    return default_backend()
  File "/usr/local/lib/python3.8/site-packages/cryptography/hazmat/backends/__init__.py", line 15, in default_backend
    from cryptography.hazmat.backends.openssl.backend import backend
  File "/usr/local/lib/python3.8/site-packages/cryptography/hazmat/backends/openssl/__init__.py", line 7, in <module>
    from cryptography.hazmat.backends.openssl.backend import backend
  File "/usr/local/lib/python3.8/site-packages/cryptography/hazmat/backends/openssl/backend.py", line 117, in <module>
    from cryptography.hazmat.bindings.openssl import binding
  File "/usr/local/lib/python3.8/site-packages/cryptography/hazmat/bindings/openssl/binding.py", line 15, in <module>
    from cryptography.hazmat.bindings._openssl import ffi, lib
ModuleNotFoundError: No module named '_cffi_backend'

**Comment by khatkar** [comment]
@sarangdharmapurikar1  The new library does not support `verify` param. Try this:
```python
jwt.decode(encoded_jwt, algorithms=["RS256"], options={"verify_signature": False})
```
