### ISSUE TITLE
AudienceError

### ISSUE THREAD

**Issue by GarryGaller** [jpadilla/pyjwt#622]
```
>>> import jwt
>>> encoded = jwt.encode({"some": "payload"}, "secret", algorithm="HS256")
>>> jwt.decode(encoded, "secret", algorithms=["HS256"])
{'some': 'payload'}
>>> encoded = jwt.encode({"aud":"12345", "some": "payload"}, "secret", algorithm="HS256")
>>> jwt.decode(encoded, "secret", algorithms=["HS256"])
Traceback (most recent call last):
  File "<pyshell#4>", line 1, in <module>
    jwt.decode(encoded, "secret", algorithms=["HS256"])
  File "F:\INSTALL\Python38\lib\site-packages\jwt\api_jwt.py", line 113, in decode
    decoded = self.decode_complete(jwt, key, algorithms, options, **kwargs)
  File "F:\INSTALL\Python38\lib\site-packages\jwt\api_jwt.py", line 100, in decode_complete
    self._validate_claims(payload, merged_options, **kwargs)
  File "F:\INSTALL\Python38\lib\site-packages\jwt\api_jwt.py", line 142, in _validate_claims
    self._validate_aud(payload, audience)
  File "F:\INSTALL\Python38\lib\site-packages\jwt\api_jwt.py", line 185, in _validate_aud
    raise InvalidAudienceError("Invalid audience")
jwt.exceptions.InvalidAudienceError: Invalid audience
>>> 
```

**Comment by dajiaji** [comment]
@GarryGaller in the current implementation, I think you need to specify `audience` parameter on decoce() as follows:

```
>>> encoded = jwt.encode({"aud":"12345", "some": "payload"}, "secret", algorithm="HS256")
>>> jwt.decode(encoded, "secret", algorithms=["HS256"], audience="12345")
{'aud': '12345', 'some': 'payload'}
```

**Comment by dajiaji** [comment]
Or 

```
>>> encoded = jwt.encode({"aud":"12345", "some": "payload"}, "secret", algorithm="HS256")
>>> jwt.decode(encoded, "secret", algorithms=["HS256"], options={"verify_aud": False})
{'aud': '12345', 'some': 'payload'}
```

Anyway, I think this issue doesn't have any problem.  @jpadilla @auvipy you can close this issue.
